# Generated by Django 4.2.2 on 2023-06-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininginstance',
            name='observations',
            field=models.TextField(blank=True, help_text='Enter any observation about this month', max_length=1000),
        ),
    ]
