# Generated by Django 4.2.2 on 2023-06-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_alter_traininginstance_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininginstance',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
