# Generated by Django 4.2.2 on 2023-06-15 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_rename_trainer_id_clientprofile_personal_trainer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainerprofile',
            options={'permissions': [('personal_trainer', 'Can have access to personal trainer data')]},
        ),
    ]
