# Generated by Django 4.2.2 on 2023-06-24 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0007_alter_trainerprofile_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traininginstance',
            old_name='client_id',
            new_name='client',
        ),
    ]
