# Generated by Django 4.2.2 on 2023-06-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0008_rename_client_id_traininginstance_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
