# Generated by Django 4.2.2 on 2023-06-26 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0009_clientprofile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientprofile',
            old_name='email',
            new_name='client_email',
        ),
    ]
