# Generated by Django 4.2.2 on 2023-07-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0010_rename_email_clientprofile_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininginstance',
            name='class10_status',
            field=models.CharField(blank=True, choices=[('ok', 'Done!'), ('no', 'No'), ('gc', 'Given Class'), ('hd', 'Holiday'), ('na', '-')], help_text='Class status', max_length=2),
        ),
        migrations.AlterField(
            model_name='traininginstance',
            name='class11_status',
            field=models.CharField(blank=True, choices=[('ok', 'Done!'), ('no', 'No'), ('gc', 'Given Class'), ('hd', 'Holiday'), ('na', '-')], help_text='Class status', max_length=2),
        ),
        migrations.AlterField(
            model_name='traininginstance',
            name='class12_status',
            field=models.CharField(blank=True, choices=[('ok', 'Done!'), ('no', 'No'), ('gc', 'Given Class'), ('hd', 'Holiday'), ('na', '-')], help_text='Class status', max_length=2),
        ),
        migrations.AlterField(
            model_name='traininginstance',
            name='class13_status',
            field=models.CharField(blank=True, choices=[('ok', 'Done!'), ('no', 'No'), ('gc', 'Given Class'), ('hd', 'Holiday'), ('na', '-')], help_text='Class status', max_length=2),
        ),
        migrations.AlterField(
            model_name='traininginstance',
            name='class14_status',
            field=models.CharField(blank=True, choices=[('ok', 'Done!'), ('no', 'No'), ('gc', 'Given Class'), ('hd', 'Holiday'), ('na', '-')], help_text='Class status', max_length=2),
        ),
        migrations.AlterField(
            model_name='traininginstance',
            name='class15_status',
            field=models.CharField(blank=True, choices=[('ok', 'Done!'), ('no', 'No'), ('gc', 'Given Class'), ('hd', 'Holiday'), ('na', '-')], help_text='Class status', max_length=2),
        ),
        migrations.AlterField(
            model_name='traininginstance',
            name='class16_status',
            field=models.CharField(blank=True, choices=[('ok', 'Done!'), ('no', 'No'), ('gc', 'Given Class'), ('hd', 'Holiday'), ('na', '-')], help_text='Class status', max_length=2),
        ),
        migrations.AlterField(
            model_name='traininginstance',
            name='class1_status',
            field=models.CharField(blank=True, choices=[('ok', 'Done!'), ('no', 'No'), ('gc', 'Given Class'), ('hd', 'Holiday'), ('na', '-')], help_text='Class status', max_length=2),
        ),
        migrations.AlterField(
            model_name='traininginstance',
            name='class2_status',
            field=models.CharField(blank=True, choices=[('ok', 'Done!'), ('no', 'No'), ('gc', 'Given Class'), ('hd', 'Holiday'), ('na', '-')], help_text='Class status', max_length=2),
        ),
        migrations.AlterField(
            model_name='traininginstance',
            name='class3_status',
            field=models.CharField(blank=True, choices=[('ok', 'Done!'), ('no', 'No'), ('gc', 'Given Class'), ('hd', 'Holiday'), ('na', '-')], help_text='Class status', max_length=2),
        ),
        migrations.AlterField(
            model_name='traininginstance',
            name='class4_status',
            field=models.CharField(blank=True, choices=[('ok', 'Done!'), ('no', 'No'), ('gc', 'Given Class'), ('hd', 'Holiday'), ('na', '-')], help_text='Class status', max_length=2),
        ),
        migrations.AlterField(
            model_name='traininginstance',
            name='class5_status',
            field=models.CharField(blank=True, choices=[('ok', 'Done!'), ('no', 'No'), ('gc', 'Given Class'), ('hd', 'Holiday'), ('na', '-')], help_text='Class status', max_length=2),
        ),
        migrations.AlterField(
            model_name='traininginstance',
            name='class6_status',
            field=models.CharField(blank=True, choices=[('ok', 'Done!'), ('no', 'No'), ('gc', 'Given Class'), ('hd', 'Holiday'), ('na', '-')], help_text='Class status', max_length=2),
        ),
        migrations.AlterField(
            model_name='traininginstance',
            name='class7_status',
            field=models.CharField(blank=True, choices=[('ok', 'Done!'), ('no', 'No'), ('gc', 'Given Class'), ('hd', 'Holiday'), ('na', '-')], help_text='Class status', max_length=2),
        ),
        migrations.AlterField(
            model_name='traininginstance',
            name='class8_status',
            field=models.CharField(blank=True, choices=[('ok', 'Done!'), ('no', 'No'), ('gc', 'Given Class'), ('hd', 'Holiday'), ('na', '-')], help_text='Class status', max_length=2),
        ),
        migrations.AlterField(
            model_name='traininginstance',
            name='class9_status',
            field=models.CharField(blank=True, choices=[('ok', 'Done!'), ('no', 'No'), ('gc', 'Given Class'), ('hd', 'Holiday'), ('na', '-')], help_text='Class status', max_length=2),
        ),
    ]
